const SCOPES_SKILLS_READWRITE = 'alexa::ask:skills:readwrite'
const SCOPES_MODELS_READWRITE = 'alexa::ask:models:readwrite'
const SCOPES_SKILLS_TEST = 'alexa::ask:skills:test'
const SCOPES_CATALOG_READ = 'alexa::ask:catalogs:read'
const SCOPES_CATALOG_READWRITE = 'alexa::ask:catalogs:readwrite'

module.exports.LWA = {
  AUTHORIZE_HOST: 'https://www.amazon.com',
  AUTHORIZE_PATH: '/ap/oa',
  TOKEN_HOST: 'https://api.amazon.com',
  TOKEN_PATH: '/auth/o2/token',
  S3_RESPONSE_PARSER_URL: 'https://s3.amazonaws.com/ask-cli/response_parser.html',
  DEFAULT_STATE: 'Ask-SkillModel-ReadWrite',
  DEFAULT_SCOPES: `${SCOPES_SKILLS_READWRITE} ${SCOPES_MODELS_READWRITE} ${SCOPES_SKILLS_TEST} ${SCOPES_CATALOG_READ} ${SCOPES_CATALOG_READWRITE}`
}
module.exports.SMAPI = {
  BASE_URLS: {
    NA: 'https://api.amazonalexa.com',
    EU: 'https://api.eu.amazonalexa.com',
    FE: 'https://api.fe.amazonalexa.com'
  },
  API_VERSION: 'v1'
}
module.exports.SIMULATION_STATUS = {
  SUCCESSFUL: 'SUCCESSFUL',
  FAILED: 'FAILED',
  IN_PROGRESS: 'IN_PROGRESS'
}
module.exports.Capabilities = {
  ALEXA_SMAPI_API: 'ALEXA_SMAPI_API',
  ALEXA_SMAPI_BASE_URL: 'ALEXA_SMAPI_BASE_URL',
  ALEXA_SMAPI_SKILLID: 'ALEXA_SMAPI_SKILLID',
  ALEXA_SMAPI_LOCALE: 'ALEXA_SMAPI_LOCALE',
  ALEXA_SMAPI_REFRESHTOKEN: 'ALEXA_SMAPI_REFRESHTOKEN',
  ALEXA_SMAPI_ACCESSTOKEN: 'ALEXA_SMAPI_ACCESSTOKEN',
  ALEXA_SMAPI_CLIENTID: 'ALEXA_SMAPI_CLIENTID',
  ALEXA_SMAPI_CLIENTSECRET: 'ALEXA_SMAPI_CLIENTSECRET',
  ALEXA_SMAPI_VENDORID: 'ALEXA_SMAPI_VENDORID',
  ALEXA_SMAPI_ENDPOINTREGION: 'ALEXA_SMAPI_ENDPOINTREGION',
  ALEXA_SMAPI_INVOCATION_TEXT_INTENT: 'ALEXA_SMAPI_INVOCATION_TEXT_INTENT',
  ALEXA_SMAPI_INVOCATION_TEXT_SLOT: 'ALEXA_SMAPI_INVOCATION_TEXT_SLOT',
  ALEXA_SMAPI_INVOCATION_REQUEST_TEMPLATE: 'ALEXA_SMAPI_INVOCATION_REQUEST_TEMPLATE',
  ALEXA_SMAPI_AUDIO_CAPABILITY: 'ALEXA_SMAPI_AUDIO_CAPABILITY',
  ALEXA_SMAPI_DISPLAY_CAPABILITY: 'ALEXA_SMAPI_DISPLAY_CAPABILITY',
  ALEXA_SMAPI_REFRESH_USER_ID: 'ALEXA_SMAPI_REFRESH_USER_ID',
  ALEXA_SMAPI_KEEP_AUDIO_PLAYER_STATE: 'ALEXA_SMAPI_KEEP_AUDIO_PLAYER_STATE'
}
module.exports.Defaults = {
  ALEXA_SMAPI_API: 'simulation',
  ALEXA_SMAPI_LOCALE: 'en-US',
  ALEXA_SMAPI_ENDPOINTREGION: 'default',
  ALEXA_SMAPI_BASE_URL: 'https://api.amazonalexa.com'
}
